### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by MohammadShahdad** [asdacap/iiumschedule#7]
The build succeeds but the app doesn't start and keeps exiting with the following error

Traceback (most recent call last):
  File "app.py", line 19, in <module>
    import bootstrap
  File "/app/bootstrap.py", line 30, in <module>
    from flask_sqlalchemy import SQLAlchemy
  File "/app/server/lib/flask_sqlalchemy/__init__.py", line 25, in <module>
    from sqlalchemy.orm.exc import UnmappedClassError
ImportError: cannot import name UnmappedClassError

**Comment by asdacap** [comment]
What command did you use exactly?

**Comment by MohammadShahdad** [comment]
docker-compose build

To build the code and then

docker-compose up -d

That error I sent before I checked from the logs

**Comment by asdacap** [comment]
How about this as the docker-compose?
```
version: '2'
services:
  main:
    build: .
    ports:
      - "3070:5000"
    volumes:
      - log:/app/log/
    depends_on:
      - db
  cron:
    build: .
    volumes:
      - log:/app/log/
    command: start-cron
  db:
    image: postgres:9
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      # Obviously, don't use this for production
      - POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  database_data:
  log:
```
